services:
  web:
    build:
      context: .
      args:
        - DEV=true
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "while ! pg_isready -h db -p 5432 -U myuser; do sleep 1; done && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword

    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dev_db_data:
