---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest # Use the most up-to-date runner

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: docker-compose run --rm web sh -c "pytest"

      - name: Run Linter
        run: docker-compose run --rm web sh -c "flake8"
